name: Benchmarks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  benchmark-main:
    name: Benchmark (Main)
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository_owner == 'arcuru'
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - name: Setup Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: eidetica
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Install Bencher CLI
        uses: bencherdev/bencher@886fbed6aad69e12a7852b0fc9ce49c50516c578 # main

      - name: Run Benchmarks
        run: |
          nix develop --command bencher run \
            --project eidetica \
            --token '${{ secrets.BENCHER_API_TOKEN }}' \
            --branch main \
            --testbed ubuntu-latest \
            --adapter rust_criterion \
            --err \
            "cargo bench --workspace"

  benchmark-pr:
    name: Benchmark (PR)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.repository_owner == 'arcuru'
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@c5a866b6ab867e88becbed4467b93592bce69f8a # v21

      - name: Setup Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: eidetica
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Install Bencher CLI
        uses: bencherdev/bencher@886fbed6aad69e12a7852b0fc9ce49c50516c578 # main

      - name: Run Benchmarks
        run: |
          nix develop --command bencher run \
            --project eidetica \
            --token '${{ secrets.BENCHER_API_TOKEN }}' \
            --branch "$HEAD_REF" \
            --start-point main \
            --start-point-clone-thresholds \
            --start-point-reset \
            --testbed ubuntu-latest \
            --adapter rust_criterion \
            --err \
            --github-actions '${{ secrets.GITHUB_TOKEN }}' \
            "cargo bench --workspace"
        env:
          HEAD_REF: ${{ github.head_ref }}
